---
proxy-groups:
- name: AksesData
  type: select
  interface-name: eth1
  proxies:
  - DIRECT
- name: Starlink
  type: select
  interface-name: phy0-sta0
  proxies:
  - DIRECT
- name: via-akses
  type: fallback
  proxies:
  - AksesData
  - Starlink
- name: via-Starkink
  type: fallback
  proxies:
  - Starlink
  - AksesData
port: 7890
socks-port: 7891
mixed-port: 7893
redir-port: 7892
tproxy-port: 7895
geodata-mode: true
geodata-loader: memconservative
tcp-concurrent: true
allow-lan: true
bind-address: "*"
mode: rule
log-level: silent
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
secret: 123456
profile:
  store-selected: true
  store-fake-ip: false
sniffer:
  enable: true
  sniffing:
  - tls
  - http
  ForceDnsMapping: false
  ParsePureIp: true
  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssot.com"
  skip-domain:
  - "+.apple.com"
  - Mijia Cloud
  - "+.jd.com"
  port-whitelist:
  - 443
  - 80
dns:
  enable: true
  listen: 0.0.0.0:7874
  default-nameserver:
  - 1.1.1.1
  - 1.0.0.1
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - shark007.net
  nameserver:
  - https://2ut5yukgpm.cloudflare-gateway.com/dns-query
  fallback:
  - tls://2ut5yukgpm.cloudflare-gateway.com:853
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - "+.*"
  ipv6: false
rule-providers:
  RP-whatsapp:
    type: http
    behavior: classical
    path: "./rule_provider/whatsapp.yaml"
    url: https://raw.githubusercontent.com/ardiyanw/myconfig/main/rule-provider/whatsapp.yaml
  RP-bstation:
    type: http
    behavior: classical
    path: "./rule_provider/bstation.yaml"
    url: https://raw.githubusercontent.com/ardiyanw/myconfig/main/rule-provider/bstation.yaml
  RP-portgame:
    type: http
    behavior: classical
    path: "./rule_provider/portgame.yaml"
    url: https://raw.githubusercontent.com/ardiyanw/myconfig/main/rule-provider/portgame.yaml
  RP-speedtest:
    type: http
    behavior: classical
    path: "./rule_provider/speedtest.yaml"
    url: https://raw.githubusercontent.com/ardiyanw/myconfig/main/rule-provider/speedtest.yaml
  RP-zoom:
    type: http
    behavior: classical
    path: "./rule_provider/zoom.yaml"
    url: https://raw.githubusercontent.com/ardiyanw/myconfig/main/rule-provider/zoom.yaml
  RP-indo:
    type: http
    behavior: classical
    path: "./rule_provider/indo.yaml"
    url: https://raw.githubusercontent.com/ardiyanw/myconfig/main/rule-provider/indo.yaml
  RP-spotify:
    type: http
    behavior: classical
    path: "./rule_provider/spotify.yaml"
    url: https://raw.githubusercontent.com/ardiyanw/myconfig/main/rule-provider/spotify.yaml
  RP-telegram:
    type: http
    behavior: classical
    path: "./rule_provider/telegram.yaml"
    url: https://raw.githubusercontent.com/ardiyanw/myconfig/main/rule-provider/telegram.yaml
  RP-tiktok:
    type: http
    behavior: classical
    path: "./rule_provider/tiktok.yaml"
    url: https://raw.githubusercontent.com/ardiyanw/myconfig/main/rule-provider/tiktok.yaml
  RP-google:
    type: http
    behavior: classical
    path: "./rule_provider/google.yaml"
    url: https://raw.githubusercontent.com/ardiyanw/myconfig/main/rule-provider/google.yaml
rules:
- SRC-IP-CIDR,172.16.21.0/24,via-Starkink
- DST-PORT,8080,via-Starkink
- RULE-SET,RP-portgame,via-Starkink
- RULE-SET,RP-whatsapp,via-Starkink
- GEOIP,private,AksesData,no-resolve
- RULE-SET,RP-bstation,via-Starkink
- RULE-SET,RP-speedtest,via-akses
- RULE-SET,RP-zoom,via-Starkink
- RULE-SET,RP-spotify,via-Starkink
- RULE-SET,RP-telegram,via-Starkink
- GEOSITE,telegram,via-Starkink
- GEOIP,telegram,via-Starkink
- RULE-SET,RP-tiktok,via-Starkink
- RULE-SET,RP-google,via-Starkink
- GEOSITE,facebook,via-Starkink
- GEOIP,facebook,via-Starkink
- GEOSITE,google,via-Starkink
- GEOIP,google,via-Starkink
- GEOSITE,twitter,via-Starkink
- GEOIP,twitter,via-Starkink
- GEOSITE,tiktok,via-Starkink
- GEOIP,cloudflare,via-akses
- GEOSITE,cloudflare,via-akses
- GEOSITE,microsoft,via-Starkink
- RULE-SET,RP-indo,via-akses
- GEOIP,sg,via-akses
- GEOSITE,akamai,via-Starkink
- GEOIP,id,via-akses
- RULE-SET,RP-indo,via-akses
- MATCH,GLOBAL